### PR TITLE
DTPORTAL-6976 - update monolog dependency

### PR DESCRIPTION
**Pull request by alex-komisarz-dialog**
https://dialogtech.atlassian.net/browse/DTPORTAL-6976

### CODE REVIEW

**Comment by alex-komisarz-dialog** [comment]
@yadnad please review

**Review by yadnad — APPROVED** [review]

**Comment by yadnad** [comment]
@jenni this is one of the libraries we load from Composer in both CRBN and Organic. The change *should* be harmless. However, as soon as this gets merged it will get deployed to all environments including PROD during the next deployment. When this is ready to be tested please see Alex and myself to come up with a strategy to verify the changes on Test.

**Comment by catlike** [comment]
Hi Dan and Alex!

I am somehow subscribed to commits on these DT repos (backstory for Alex, I
used to work for at DT and was the primary account on the github repos at
one point) I must be buried somewhere in the repos (my handle is catlike).
No DT repos show up for me as followed repos, so I don't think I can remove
it on my end.

Anyways hope all is well and say hi to Breen, Phil, and James for me!

Take care, Robin

**Comment by yadnad** [comment]
Hi Robin,

Looks like this was a public repo that you have watched. You should be able to unwatch it.

I'll let them know you said hello 😄 

Dan

**Comment by alex-komisarz-dialog** [comment]
FYI @jalubke

**Pull request merged**
